
export const ar = {
  // General
  'preview': 'معاينة',
  'edit': 'تعديل',
  'delete': 'حذف',
  'save': 'حفظ',
  'backToList': 'العودة للقائمة',
  'createNew': 'إنشاء جديد',
  'add': 'إضافة',
  'close': 'إغلاق',
  'cancel': 'إلغاء',
  'dashboard': 'لوحة التحكم',
  'moveUp': 'نقل لأعلى',
  'moveDown': 'نقل لأسفل',
  'duplicate': 'تكرار',
  'logout': 'تسجيل الخروج',

  // Navigation
  'nav.portfolios': 'الملفات الشخصية',
  'nav.projects': 'المشاريع',
  'nav.skills': 'المهارات',
  'nav.settings': 'الإعدادات',
  'nav.resumes': 'السير الذاتية',

  // Portfolio List Page
  'welcomeBack': 'مرحباً بعودتك، {{name}}!',
  'yourPortfolios': 'ملفاتك الشخصية',
  'searchPlaceholder': 'ابحث في الملفات حسب العنوان...',
  'sortBy': 'ترتيب حسب',
  'lastModified': 'آخر تعديل',
  'dateCreated': 'تاريخ الإنشاء',
  'titleAZ': 'العنوان (أ-ي)',
  'noPortfoliosYet': 'لا يوجد ملفات شخصية بعد!',
  'getStarted': 'ابدأ بإنشاء أول ملف شخصي لك.',
  'noSearchResults': 'لا توجد ملفات تطابق بحثك',
  'tryDifferentSearch': 'جرّب كلمة بحث مختلفة.',
  'deleteConfirm': 'هل أنت متأكد من رغبتك في حذف هذا الملف؟ لا يمكن التراجع عن هذا الإجراء.',
  'published': 'منشور',
  'draft': 'مسودة',
  'updated': 'آخر تحديث',
  'viewPublic': 'عرض الصفحة العامة',
  'blocksCount': '{{count}} قسم',
  'previewTitle': 'معاينة: {{title}}',
  'closePreview': 'إغلاق المعاينة',
  'createNewPortfolio': 'إنشاء ملف شخصي جديد',
  'templateSelectionPrompt': 'اختر قالبًا للبدء، أو ابدأ بصفحة فارغة. يمكنك تخصيص كل شيء لاحقًا.',
  'selectTemplate': 'اختر القالب',
  'template.developer.name': 'ملف مطور برامج',
  'template.developer.desc': 'تصميم كلاسيكي واحترافي مثالي لمطوري ومهندسي البرمجيات. يبرز مهاراتك ومشاريعك.',
  'template.designer.name': 'ملف مصمم',
  'template.designer.desc': 'تصميم بصري موجه لمصممي تجربة المستخدم/واجهة المستخدم. يضع أعمالك الإبداعية في المقدمة.',
  'template.photographer.name': 'ملف مصور فوتوغرافي',
  'template.photographer.desc': 'قالب نظيف يركز على الصور لعرض أعمالك الفوتوغرافية مع معرض مذهل وقسم للخدمات.',
  'template.writer.name': 'ملف كاتب',
  'template.writer.desc': 'تصميم أنيق وسهل القراءة للمؤلفين والمدونين والصحفيين لعرض أعمالهم المنشورة.',
  'template.freelancer.name': 'ملف مستقل',
  'template.freelancer.desc': 'قالب متعدد الاستخدامات للاستشاريين والمستقلين لعرض الخدمات ودراسات الحالة والتوصيات.',
  'template.scratch.name': 'ابدأ من الصفر',
  'template.scratch.desc': 'صفحة بيضاء. ابدأ بملف شخصي فارغ وابنِ رؤيتك من الألف إلى الياء.',
  
  // Resume List Page
  'yourResumes': 'سيرك الذاتية',
  'searchResumesPlaceholder': 'ابحث في السير الذاتية...',
  'noResumesYet': 'لا توجد سير ذاتية بعد!',
  'getStartedResumes': 'ابدأ بإنشاء سيرتك الذاتية الأولى، أو دع الذكاء الاصطناعي ينشئها من ملف شخصي.',
  'deleteResumeConfirm': 'هل أنت متأكد من رغبتك في حذف هذه السيرة الذاتية؟ لا يمكن التراجع عن هذا الإجراء.',
  'createNewResume': 'إنشاء سيرة ذاتية جديدة',
  'resumeTitle': 'عنوان السيرة الذاتية',
  'createFromScratch': 'إنشاء من الصفر',
  'generateFromPortfolio': 'إنشاء من ملف شخصي',
  'generateFromJobDescription': 'تخصيص لوصف وظيفي',
  'selectPortfolio': 'اختر ملفًا شخصيًا للإنشاء منه',
  'generatingResume': 'جاري إنشاء السيرة الذاتية...',
  'createAndEdit': 'إنشاء وتعديل',
  'generateAndEdit': 'إنشاء وتعديل',
  'atsFriendlyNote': 'سيقوم الذكاء الاصطناعي بإنشاء سيرة ذاتية متوافقة مع أنظمة تتبع المتقدمين (ATS) ومحسّنة بالكلمات المفتاحية من الوصف الوظيفي.',
  'selectBaseResume': 'اختر سيرة ذاتية أساسية لتخصيصها',
  'pasteJobDescriptionHere': 'الصق الوصف الوظيفي الكامل هنا',
  'tailorAndEdit': 'تخصيص وتعديل',
  'generatingTailoredResume': 'جاري إنشاء السيرة الذاتية المخصصة...',
  'noResumesToTailor': 'تحتاج إلى سيرة ذاتية واحدة على الأقل لاستخدامها كأساس للتخصيص.',


  // Project Management
  'myProjects': 'مشاريعي',
  'manageYourProjects': 'عرض وإدارة جميع مشاريعك.',
  'searchProjectsPlaceholder': 'ابحث في المشاريع...',
  'noProjectsYet': 'لم تتم إضافة أي مشاريع بعد.',
  'getStartedProjects': 'أضف مشروعك الأول للبدء.',
  'createProject': 'إنشاء مشروع جديد',
  'editProject': 'تعديل المشروع',
  'projectTitle': 'عنوان المشروع',
  'projectDescription': 'الوصف',
  'projectImageUrl': 'رابط الصورة',
  'projectTechnologies': 'التقنيات',
  'technologiesHint': 'مفصولة بفاصلة (مثل: React, Node.js)',
  'projectLink': 'رابط المشروع',
  'saveProject': 'حفظ المشروع',
  'deleteProjectConfirm': 'هل أنت متأكد من رغبتك في حذف هذا المشروع؟',

  // Skill Management
  'createSkill': 'إضافة مهارة جديدة',
  'editSkill': 'تعديل المهارة',
  'skillName': 'اسم المهارة',
  'skillCategory': 'الفئة',
  'saveSkill': 'حفظ المهارة',

  // Profile Page
  'myProfile': 'ملفي الشخصي',
  'profileUpdated': 'تم تحديث الملف الشخصي بنجاح!',
  'avatarUrl': 'رابط الصورة الرمزية',
  'fullName': 'الاسم الكامل',
  'jobTitle': 'المسمى الوظيفي',
  'contactEmail': 'البريد الإلكتروني للتواصل',
  'bio': 'نبذة تعريفية',
  'updateProfile': 'تحديث الملف الشخصي',

  // Editor Page
  'untitledPortfolio': 'ملف بدون عنوان',
  'untitledResume': 'سيرة ذاتية بدون عنوان',
  'content': 'المحتوى',
  'design': 'التصميم',
  'assets': 'الأصول',
  'addNewBlock': 'إضافة قسم جديد',
  'addYourFirstBlock': 'أضف قسمك الأول',
  'block.hero': 'الواجهة (Hero)',
  'block.hero.desc': 'قسم كبير وجذاب لجذب الانتباه.',
  'block.about': 'نبذة عني',
  'block.about.desc': 'اسرد قصتك وخلفيتك المهنية.',
  'block.projects': 'المشاريع',
  'block.projects.desc': 'استعرض أفضل أعمالك.',
  'block.skills': 'المهارات',
  'block.skills.desc': 'سجل قدراتك التقنية.',
  'block.gallery': 'معرض الصور',
  'block.gallery.desc': 'استعرض مجموعة من الصور.',
  'block.testimonials': 'الآراء والتوصيات',
  'block.testimonials.desc': 'اقتباسات من العملاء أو الزملاء.',
  'block.video': 'تضمين فيديو',
  'block.video.desc': 'تضمين فيديو من يوتيوب أو فيميو.',
  'block.cta': 'دعوة لاتخاذ إجراء',
  'block.cta.desc': 'وجه الزوار إلى رابط معين.',
  'block.resume': 'السيرة الذاتية',
  'block.resume.desc': 'رابط لتنزيل سيرتك الذاتية.',
  'block.links': 'روابط خارجية',
  'block.links.desc': 'روابط لوسائل التواصل الاجتماعي أو ملفات شخصية أخرى.',
  'block.experience': 'الخبرة العملية',
  'block.experience.desc': 'استعرض تاريخك المهني أو خط زمني.',
  'block.contact': 'نموذج الاتصال',
  'block.contact.desc': 'نموذج للزوار لمراسلتك.',
  'block.code': 'مقتطف كود',
  'block.code.desc': 'اعرض كتلة منسقة من الكود البرمجي.',
  'block.services': 'الخدمات / الأسعار',
  'block.services.desc': 'اعرض خدماتك في شكل باقات أسعار.',
  'block.blog': 'المدونة / كتابات',
  'block.blog.desc': 'استعرض المقالات التي كتبتها.',
  'code.language': 'اللغة',
  'code.code': 'الكود',
  'code.copy': 'نسخ',
  'code.copied': 'تم النسخ!',
  'colorTheme': 'سمة اللون',
  'fontPairing': 'توافق الخطوط',
  'portfolioSaved': 'تم حفظ الملف!',
  'resumeSaved': 'تم حفظ السيرة الذاتية!',
  'deleteConfirmEditor': 'هل أنت متأكد من رغبتك في حذف هذا الملف؟ لا يمكن التراجع عن هذا الإجراء.',
  'toggleSidebar': 'تبديل الشريط الجانبي',
  'dragHandle': 'اسحب لإعادة الترتيب',
  'accentColor': 'اللون المميز',
  'spacing': 'التباعد',
  'cornerRadius': 'استدارة الزوايا',
  'animationStyle': 'نمط الحركة',
  'navigationStyle': 'نمط التنقل',
  'animation.none': 'بدون',
  'animation.fadeIn': 'ظهور تدريجي',
  'animation.slideInUp': 'انزلاق للأعلى',
  'animation.scaleIn': 'تكبير للداخل',
  'animation.slideInFromLeft': 'انزلاق من اليسار',
  'animation.revealUp': 'كشف لأعلى',
  'animation.blurIn': 'ظهور ضبابي',
  'navigation.none': 'بدون',
  'navigation.stickyHeader': 'شريط علوي ثابت',
  'navigation.floatingDots': 'نقاط عائمة',
  'navigation.minimalHeader': 'شريط علوي بسيط',
  'searchProjects': 'ابحث في المشاريع...',
  'searchSkills': 'ابحث في المهارات...',
  'gallery.emptyState': 'لا توجد صور بعد. ابدأ بإضافة صورتك الأولى.',
  'testimonials.emptyState': 'لا توجد توصيات بعد. انقر أدناه لإضافة واحدة.',
  'links.emptyState': 'لا توجد روابط بعد. أضف رابطًا إلى ملفاتك الاجتماعية أو المهنية.',
  'experience.emptyState': 'لا توجد عناصر خبرة بعد. أضف دورك الأول.',
  'services.emptyState': 'لا توجد باقات أسعار بعد. أضف باقتك الأولى للبدء.',
  'blog.emptyState': 'لا توجد مقالات بعد. أضف مقالك الأول.',
  'addImage': 'إضافة صورة',
  'addTestimonial': 'إضافة توصية',
  'addLink': 'إضافة رابط',
  'addExperienceItem': 'إضافة خبرة',
  'addTier': 'إضافة باقة',
  'addPost': 'إضافة مقال',
  'tierName': 'اسم الباقة (مثال: الباقة الأساسية)',
  'price': 'السعر (مثال: $99)',
  'frequency': 'الدورية (مثال: /شهر)',
  'description': 'الوصف',
  'features': 'المميزات (واحدة في كل سطر)',
  'buttonText': 'نص الزر',
  'buttonLink': 'رابط الزر',
  'markAsFeatured': 'تمييز كباقة مميزة',
  'headingFont': 'خط العناوين',
  'bodyFont': 'خط النصوص',
  'fontSize': 'حجم الخط',
  'fontSize.sm': 'ص',
  'fontSize.md': 'م',
  'fontSize.lg': 'ك',
  'pageWidth': 'عرض الصفحة',
  'pageWidth.standard': 'عادي',
  'pageWidth.full': 'كامل',
  'buttonStyle': 'نمط الأزرار',
  'buttonStyle.rounded': 'مستدير',
  'buttonStyle.pill': 'بيضاوي',
  'buttonStyle.square': 'مربع',
  'contact.name': 'اسمك',
  'contact.email': 'بريدك الإلكتروني',
  'contact.message': 'رسالتك',
  'contact.submit': 'إرسال الرسالة',
  'contact.formDisabled': 'إرسال النماذج معطل في هذه المعاينة.',

  // AI & Assets
  'aiTailor': 'مساعد السيرة الذاتية',
  'pasteJobDescription': 'الصق الوصف الوظيفي هنا',
  'generateSuggestions': 'إنشاء اقتراحات',
  'generatingSuggestions': 'جاري الإنشاء...',
  'tailoringSuggestions': 'اقتراحات التخصيص',
  'rewrittenSummary': 'الملخص المعدل',
  'suggestedKeywords': 'كلمات رئيسية مقترحة للإضافة',
  'generalFeedback': 'ملاحظات عامة',
  'applySuggestions': 'تطبيق الاقتراحات وإغلاق',
  'aiImageGeneration': 'إنشاء صورة بالذكاء الاصطناعي',
  'imagePrompt': 'وصف الصورة',
  'imagePromptPlaceholder': 'مثال: خلفية تجريدية بسيطة بألوان زرقاء وبرتقالية',
  'generate': 'إنشاء',
  'generating': 'جاري الإنشاء...',
  'generatingMessage': 'يرجى الانتظار لحظة بينما يقوم الذكاء الاصطناعي بإنشاء صورتك.',
  'useThisImage': 'إضافة إلى المكتبة',
  'generateNewImage': 'إنشاء صورة جديدة',
  'applyToBlock': 'تطبيق على القسم',
  'selectBlockToApply': 'اختر قسمًا',
  'noAssets': 'لم تقم بإنشاء أي صور بعد.',
  'getStartedAssets': "انقر على 'إنشاء صورة جديدة' لإنشاء أول أصل بصري لك.",
  'deleteAssetConfirm': 'هل أنت متأكد من رغبتك في حذف هذا الأصل؟ ستتم إزالته من أي أقسام تستخدمه.',
  'apply': 'تطبيق',
  'regenerate': 'إعادة الإنشاء',
  'aiMentor': 'المرشد الذكي',
  'aiMentor.title': 'مراجعة الملف بالذكاء الاصطناعي',
  'aiMentor.generating': 'مرشدك الذكي يراجع ملفك الشخصي...',
  'aiMentor.generating.message': 'قد يستغرق هذا بعض الوقت. نقوم بتحليل المحتوى والتصميم لتقديم ملاحظات مخصصة.',
  'aiMentor.overallImpression': 'الانطباع العام',
  'aiMentor.contentSuggestions': 'اقتراحات المحتوى',
  'aiMentor.projectShowcase': 'عرض المشاريع',
  'aiMentor.missingSections': 'إضافات مقترحة',
  'aiMentor.getReview': 'احصل على مراجعة AI',
  'aiMentor.done': 'تم',

  // Public Page
  'portfolioNotFound': 'الملف غير موجود.',
  'portfolioNotPublished': 'هذا الملف لم يتم نشره بعد.',
};