export const en = {
  // General
  'preview': 'Preview',
  'edit': 'Edit',
  'delete': 'Delete',
  'save': 'Save',
  'backToList': 'Back to List',
  'createNew': 'Create New',
  'add': 'Add',
  'close': 'Close',
  'cancel': 'Cancel',
  'dashboard': 'Dashboard',
  'moveUp': 'Move up',
  'moveDown': 'Move down',
  'duplicate': 'Duplicate',
  'logout': 'Logout',

  // Navigation
  'nav.portfolios': 'Portfolios',
  'nav.projects': 'Projects',
  'nav.skills': 'Skills',
  'nav.settings': 'Settings',
  'nav.resumes': 'Resumes',
  'nav.templates': 'Templates',
  'nav.support': 'Support & Feedback',

  // Portfolio List Page
  'welcomeBack': 'Welcome back, {{name}}!',
  'yourPortfolios': 'Your Portfolios',
  'searchPlaceholder': 'Search portfolios by title...',
  'sortBy': 'Sort by',
  'lastModified': 'Last Modified',
  'dateCreated': 'Date Created',
  'titleAZ': 'Title (A-Z)',
  'noPortfoliosYet': 'No portfolios yet!',
  'getStarted': 'Get started by creating your first portfolio.',
  'noSearchResults': 'No portfolios match your search',
  'tryDifferentSearch': 'Try a different search term.',
  'deleteConfirm': 'Are you sure you want to delete this portfolio? This cannot be undone.',
  'published': 'Published',
  'draft': 'Draft',
  'updated': 'Updated',
  'viewPublic': 'View Public',
  'blocksCount': '{{count}} blocks',
  'previewTitle': 'Preview: {{title}}',
  'closePreview': 'Close preview',
  'createNewPortfolio': 'Create a New Portfolio',
  'templateSelectionPrompt': 'Choose a template to get started, or begin with a blank canvas. You can customize everything later.',
  'selectTemplate': 'Select Template',
  'template.developer.name': 'Modern Developer',
  'template.developer.desc': 'A sleek, dark-mode template with parallax effects and shape dividers. Perfect for showcasing projects, skills, and code snippets.',
  'template.designer.name': 'Creative Designer',
  'template.designer.desc': 'An elegant, spacious, and typography-focused design. Ideal for visual portfolios with a stunning masonry gallery and sticky image sections.',
  'template.photographer.name': 'Immersive Photographer',
  'template.photographer.desc': 'A full-width, dramatic template with video backgrounds and floating-dot navigation that puts your images front and center.',
  'template.writer.name': 'Classic Writer',
  'template.writer.desc': 'A refined, reader-friendly layout with serif fonts and a relaxed line height. Built to feature your articles and publications.',
  'template.freelancer.name': 'Professional Freelancer',
  'template.freelancer.desc': 'A clean, business-oriented template designed for conversion. Highlights services, testimonials, and case studies to attract clients.',
  'template.minimalist.name': 'Minimalist Dark',
  'template.minimalist.desc': 'A clean, dark-mode slate. The perfect, unopinionated starting point to build your vision from the ground up.',
  'template.innovator.name': 'The Innovator',
  'template.innovator.desc': 'A futuristic, tech-focused design with a full-width layout, video background, and sharp, modern typography. Ideal for AI researchers or developers.',
  'template.consultant.name': 'The Consultant',
  'template.consultant.desc': 'An elegant and professional aesthetic with classic serif fonts and a spacious layout. Perfect for strategists and high-end freelancers.',
  'template.bold.name': 'The Bold Minimalist',
  'template.bold.desc': 'A stark, high-contrast design with a brutalist-inspired aesthetic. Makes a strong, unapologetic statement for artists and creatives.',
  
  // Template Showcase Page
  'templates.title': 'Choose Your Starting Point',
  'templates.subtitle': 'Select a professionally designed template to kickstart your portfolio. You can customize everything later.',
  'useTemplate': 'Use Template',
  'chooseTemplateManually': 'or, choose a template manually',

  // Resume List Page
  'yourResumes': 'Your Resumes',
  'searchResumesPlaceholder': 'Search resumes...',
  'noResumesYet': 'No resumes yet!',
  'getStartedResumes': 'Get started by creating your first resume, or let AI build one from a portfolio.',
  'deleteResumeConfirm': 'Are you sure you want to delete this resume? This cannot be undone.',
  'createNewResume': 'Create New Resume',
  'resumeTitle': 'Resume Title',
  'createFromScratch': 'Create from Scratch',
  'generateFromPortfolio': 'Generate from Portfolio',
  'generateFromJobDescription': 'Tailor for Job Description',
  'selectPortfolio': 'Select a portfolio to generate from',
  'generatingResume': 'Generating Resume...',
  'createAndEdit': 'Create & Edit',
  'generateAndEdit': 'Generate & Edit',
  'atsFriendlyNote': "Our AI will generate an ATS-friendly resume optimized with keywords from the job description.",
  'selectBaseResume': "Select a base resume to tailor from",
  'pasteJobDescriptionHere': "Paste the full job description here",
  'tailorAndEdit': "Tailor & Edit",
  'generatingTailoredResume': "Generating Tailored Resume...",
  'noResumesToTailor': "You need at least one resume to use as a base for tailoring.",


  // Project Management
  'myProjects': 'My Projects',
  'manageYourProjects': 'View and manage all your projects.',
  'searchProjectsPlaceholder': 'Search projects...',
  'noProjectsYet': 'No projects added yet.',
  'getStartedProjects': 'Add your first project to get started.',
  'createProject': 'Create New Project',
  'editProject': 'Edit Project',
  'projectTitle': 'Project Title',
  'projectDescription': 'Description',
  'projectImageUrl': 'Image URL',
  'projectTechnologies': 'Technologies',
  'technologiesHint': 'Comma-separated (e.g., React, Node.js)',
  'projectLink': 'Project Link',
  'saveProject': 'Save Project',
  'deleteProjectConfirm': 'Are you sure you want to delete this project?',

  // Skill Management
  'createSkill': 'Create New Skill',
  'editSkill': 'Edit Skill',
  'skillName': 'Skill Name',
  'skillCategory': 'Category',
  'saveSkill': 'Save Skill',

  // Profile Page
  'myProfile': 'My Profile',
  'profileUpdated': 'Profile updated successfully!',
  'avatarUrl': 'Avatar URL',
  'fullName': 'Full Name',
  'jobTitle': 'Job Title',
  'contactEmail': 'Contact Email',
  'bio': 'Bio',
  'updateProfile': 'Update Profile',


  // Editor Page
  'untitledPortfolio': 'Untitled Portfolio',
  'untitledResume': 'Untitled Resume',
  'content': 'Content',
  'design': 'Design',
  'assets': 'Assets',
  'addNewBlock': 'Add New Block',
  'addYourFirstBlock': 'Add Your First Block',
  'block.hero': 'Hero',
  'block.hero.desc': 'A big, bold section to grab attention.',
  'block.about': 'About',
  'block.about.desc': 'Tell your story and background.',
  'block.projects': 'Projects',
  'block.projects.desc': 'Showcase your best work.',
  'block.skills': 'Skills',
  'block.skills.desc': 'List your technical capabilities.',
  'block.gallery': 'Image Gallery',
  'block.gallery.desc': 'Showcase a collection of images.',
  'block.testimonials': 'Testimonials',
  'block.testimonials.desc': 'Quotes from clients or colleagues.',
  'block.video': 'Video Embed',
  'block.video.desc': 'Embed a video from YouTube/Vimeo.',
  'block.cta': 'Call to Action',
  'block.cta.desc': 'Drive visitors to a specific link.',
  'block.resume': 'Resume/CV',
  'block.resume.desc': 'Link to your downloadable resume.',
  'block.links': 'External Links',
  'block.links.desc': 'Link to social media or other profiles.',
  'block.experience': 'Experience',
  'block.experience.desc': 'Showcase work history or a timeline.',
  'block.contact': 'Contact Form',
  'block.contact.desc': 'A form for visitors to message you.',
  'block.code': 'Code Snippet',
  'block.code.desc': 'Display a formatted block of code.',
  'block.services': 'Services / Pricing',
  'block.services.desc': 'Outline your offerings in pricing tiers.',
  'block.blog': 'Blog / Writing',
  'block.blog.desc': "Feature articles you've written.",
  'code.language': 'Language',
  'code.code': 'Code',
  'code.copy': 'Copy',
  'code.copied': 'Copied!',
  'colorTheme': 'Color Theme',
  'fontPairing': 'Font Pairing',
  'portfolioSaved': 'Portfolio saved!',
  'resumeSaved': 'Resume saved!',
  'deleteConfirmEditor': 'Are you sure you want to delete this portfolio? This action cannot be undone.',
  'toggleSidebar': 'Toggle sidebar',
  'dragHandle': 'Drag to reorder',
  'accentColor': 'Accent Color',
  'spacing': 'Spacing',
  'gridGap': 'Grid Gap',
  'cornerRadius': 'Corner Radius',
  'animationStyle': 'Animation Style',
  'navigationStyle': 'Navigation Style',
  'logoPosition': 'Logo Position',
  'position.left': 'Left',
  'position.center': 'Center',
  'animation.none': 'None',
  'animation.fadeIn': 'Fade In',
  'animation.slideInUp': 'Slide In Up',
  'animation.scaleIn': 'Scale In',
  'animation.slideInFromLeft': 'Slide In From Left',
  'animation.revealUp': 'Reveal Up',
  'animation.blurIn': 'Blur In',
  'navigation.none': 'None',
  'navigation.stickyHeader': 'Sticky Header',
  'navigation.floatingDots': 'Floating Dots',
  'navigation.minimalHeader': 'Minimal Header',
  'searchProjects': 'Search projects...',
  'searchSkills': 'Search skills...',
  'gallery.emptyState': 'No images yet. Start by adding your first image.',
  'testimonials.emptyState': 'No testimonials yet. Click below to add one.',
  'links.emptyState': 'No links yet. Add a link to your social or professional profiles.',
  'experience.emptyState': 'No experience items yet. Add your first role.',
  'services.emptyState': 'No pricing tiers yet. Add one to get started.',
  'blog.emptyState': "No posts yet. Add your first article.",
  'addImage': 'Add Image',
  'addTestimonial': 'Add Testimonial',
  'addLink': 'Add Link',
  'addExperienceItem': 'Add Experience Item',
  'addTier': 'Add Tier',
  'addPost': 'Add Post',
  'tierName': 'Tier Name (e.g., Basic Plan)',
  'price': 'Price (e.g., $99)',
  'frequency': 'Frequency (e.g., /mo)',
  'description': 'Description',
  'features': 'Features (one per line)',
  'buttonText': 'Button Text',
  'buttonLink': 'Button Link',
  'markAsFeatured': 'Mark as Featured',
  'headingFont': 'Heading Font',
  'bodyFont': 'Body Font',
  'fontSize': 'Font Size',
  'fontSize.sm': 'S',
  'fontSize.md': 'M',
  'fontSize.lg': 'L',
  'pageWidth': 'Page Width',
  'pageWidth.standard': 'Standard',
  'pageWidth.full': 'Full',
  'buttonStyle': 'Button Style',
  'buttonStyle.rounded': 'Rounded',
  'buttonStyle.pill': 'Pill',
  'buttonStyle.square': 'Square',
  'contact.name': 'Your Name',
  'contact.email': 'Your Email',
  'contact.message': 'Your Message',
  'contact.submit': 'Send Message',
  'contact.formDisabled': 'Form submission is disabled in this preview.',
  'mobileMenuStyle': 'Mobile Menu Style',
  'mobileMenuAnimation': 'Mobile Menu Animation',
  'style.overlay': 'Overlay',
  'style.drawer': 'Drawer',
  'animation.slideIn': 'Slide In',
  'designPresets': 'Design Presets',
  'saveCurrentDesign': 'Save Current Design',
  'applyPreset': 'Apply',
  'presetName': 'Preset Name',
  'savePreset': 'Save Preset',
  'deletePresetConfirm': 'Are you sure you want to delete this design preset?',

  // AI & Assets
  'aiTailor': 'AI Tailor',
  'pasteJobDescription': 'Paste Job Description Here',
  'generateSuggestions': 'Generate Suggestions',
  'generatingSuggestions': 'Generating...',
  'tailoringSuggestions': 'Tailoring Suggestions',
  'rewrittenSummary': 'Rewritten Summary',
  'suggestedKeywords': 'Suggested Keywords to Add',
  'generalFeedback': 'General Feedback',
  'applySuggestions': 'Apply Suggestions & Close',
  'aiImageGeneration': 'AI Image Generation',
  'imagePrompt': 'Image Prompt',
  'imagePromptPlaceholder': 'e.g., A minimalist abstract background with teal and amber colors',
  'generate': 'Generate',
  'generating': 'Generating...',
  'generatingMessage': 'Please wait a moment while the AI creates your image.',
  'useThisImage': 'Add to Library',
  'generateNewImage': 'Generate New Image',
  'applyToBlock': 'Apply to block',
  'selectBlockToApply': 'Select a block',
  'noAssets': "You haven't generated any images yet.",
  'getStartedAssets': "Click 'Generate New Image' to create your first visual asset.",
  'deleteAssetConfirm': 'Are you sure you want to delete this asset? It will be removed from any blocks using it.',
  'apply': 'Apply',
  'regenerate': 'Re-generate',
  'aiAssistant.title': 'AI Portfolio Review',
  'aiAssistant.generating': 'Your AI assistant is reviewing your portfolio...',
  'aiAssistant.generating.message': 'This may take a moment. We are analyzing your content and design to provide personalized feedback.',
  'aiAssistant.overallImpression': 'Overall Impression',
  'aiAssistant.contentSuggestions': 'Content Suggestions',
  'aiAssistant.projectShowcase': 'Project Showcase',
  'aiAssistant.missingSections': 'Suggested Additions',
  'aiAssistant.getReview': 'Get AI Review',
  'aiAssistant.done': 'Done',

  // Admin
  'admin.settings.title': 'Platform Settings',
  'admin.settings.subtitle': 'Manage global settings, feature flags, and announcements.',
  'admin.settings.announcements.title': 'Global Announcement Banner',
  'admin.settings.announcements.enable': 'Enable Banner',
  'admin.settings.announcements.text': 'Banner Text',
  'admin.settings.announcements.preview': 'Banner Preview',
  'admin.settings.featureFlags.title': 'Feature Flags',
  'admin.settings.subscriptions.title': 'Subscription Settings',
  'admin.settings.subscriptions.proPrice': 'Pro Plan Monthly Price ($)',
  'admin.settings.save': 'Save Settings',
  'admin.settings.saveSuccess': 'Settings saved successfully!',

  // Public Page
  'portfolioNotFound': 'Portfolio not found.',
  'portfolioNotPublished': 'This portfolio is not yet published.',
};